## Pandas Profiling

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

c:\Users\ishan\anaconda3\Lib\site-packages\seaborn\_statistics.py:32: UserWarning: A NumPy version >=1.23.5 and <2.5.0 is required for this version of SciPy (detected version 2.5.0)
  from scipy.stats import gaussian_kde

In [3]:
df = pd.read_csv("StudentPerformanceFactors.csv")

In [4]:
df.sample(5)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
1786,18,91,Low,High,Yes,9,81,High,Yes,4,High,Medium,Public,Neutral,5,No,High School,Moderate,Male,71
3392,20,89,High,High,Yes,8,52,Low,Yes,2,Medium,Medium,Public,Negative,3,No,College,Moderate,Female,69
6488,22,87,High,High,Yes,8,64,Medium,No,2,Medium,High,Public,Negative,3,No,High School,Moderate,Female,70
4206,23,88,High,Low,Yes,6,58,Medium,Yes,2,Low,Medium,Public,Neutral,2,No,High School,Moderate,Male,68
3829,23,73,Low,High,No,5,60,High,Yes,1,Medium,Medium,Private,Positive,2,No,Postgraduate,Near,Female,67

In [5]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [6]:
df.shape

(6607, 20)

In [7]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [8]:
df.dropna(subset=["Teacher_Quality","Parental_Education_Level","Distance_from_Home"], inplace=True)

In [13]:
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [14]:
df["Distance_from_Home"].unique()

array(['Near', 'Moderate', 'Far'], dtype=object)

In [17]:
df["Parental_Education_Level"].unique()

array(['High School', 'College', 'Postgraduate'], dtype=object)

In [15]:
X = df.iloc[:, 16:18]

In [16]:
X

     Parental_Education_Level Distance_from_Home
0                 High School               Near
1                     College           Moderate
2                Postgraduate               Near
3                 High School           Moderate
4                     College               Near
...                       ...                ...
6602              High School               Near
6603              High School               Near
6604             Postgraduate               Near
6605              High School                Far
6606             Postgraduate               Near

[6378 rows x 2 columns]

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, df.iloc[:, -1], test_size=0.2, random_state=42)

In [20]:
X_train

     Parental_Education_Level Distance_from_Home
2356              High School           Moderate
4758                  College           Moderate
2281              High School           Moderate
485              Postgraduate               Near
4200              High School               Near
...                       ...                ...
3904             Postgraduate               Near
5378              High School               Near
5415             Postgraduate           Moderate
5582                  College               Near
894              Postgraduate                Far

[5102 rows x 2 columns]

In [24]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[["High School", "College", "Postgraduate"], ["Near", "Moderate", "Far"]])

In [25]:
oe.fit(X_train)

OrdinalEncoder(categories=[['High School', 'College', 'Postgraduate'],
                           ['Near', 'Moderate', 'Far']])

In [26]:
oe.transform(X_train)
oe.transform(X_test)

array([[0., 2.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [1., 0.],
       [1., 1.]], shape=(1276, 2))